window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Startup Mode (changes require restart)
  startup_mode: Windowed

font:
  normal:
    family: Consolas
    style: Regular

  bold:
    family: Consolas
    style: Bold

  italic:
    family: Consolas
    style: Italic

  bold_italic:
    family: Consolas
    style: Italic

  size: 14.0

live_config_reload: true

colors:
  primary:
    background: '0x191919'
    foreground: '0xeaeaea'

  cursor:
    text:   '0xf1c1c1'

# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
    - { key: T,          mods: Command,       chars: "\x10\x63" }  #1063
    - { key: D,          mods: Command,       chars: "\x10\x64" }  #1064
    - { key: F,          mods: Command,       chars: "\x10\x2c" }  #102c
    - { key: Backslash,  mods: Command,       chars: "\x10\x7c" }  #107c
    - { key: Minus,      mods: Command,       chars: "\x10\x2d" }  #102d
    - { key: Key1,       mods: Command,       chars: "\x10\x31" }  #1031
    - { key: Key2,       mods: Command,       chars: "\x10\x32" }  #1032
    - { key: Key3,       mods: Command,       chars: "\x10\x33" }  #1033
    - { key: Key4,       mods: Command,       chars: "\x10\x34" }  #1034
    - { key: Key5,       mods: Command,       chars: "\x10\x35" }  #1035
    - { key: Up,         mods: Command,       chars: "\x10\x1b\x5b\x41" } #101b5b41
    - { key: Down,       mods: Command,       chars: "\x10\x1b\x5b\x42" } #101b5b42
    - { key: Right,      mods: Command,       chars: "\x10\x1b\x5b\x43" } #101b5b43
    - { key: Left,       mods: Command,       chars: "\x10\x1b\x5b\x44" } #101b5b44

